<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-C7332C5" failures="1" tests="5" name="Personal Loan" time="0.249" errors="0" timestamp="2023-06-14T12:58:28 IST">
  <testcase classname="Test.Day1" name="Demo" time="0.031">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Day1.Demo(Day1.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="Test.Day2" name="ploan" time="0.006"/>
  <testcase classname="Test.Day4" name="LoginAPIHomeLoan" time="0.011"/>
  <testcase classname="Test.Day4" name="MobileloginHomeLoan" time="0.004"/>
  <testcase classname="Test.Day4" name="WebloginHomeLoan" time="0.008"/>
  <testcase classname="Test.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
